[package]
name = "yamlpath"
version = "0.17.0"
description = "Format-preserving YAML feature extraction"
repository = "https://github.com/zizmorcore/zizmor/tree/main/crates/yamlpath"
readme = "README.md"
keywords = ["yaml"]

authors.workspace = true
homepage.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
tree-sitter.workspace = true
tree-sitter-yaml = "0.7.0"

[dev-dependencies]
serde.workspace = true
serde_yaml.workspace = true
