[workspace]
resolver = "2"
members = ["crates/zizmor"]

[workspace.package]
authors = ["William Woodruff <william@yossarian.net>"]
readme = "README.md"
edition = "2024"
license = "MIT"

[profile.dev.package]
insta.opt-level = 3

[profile.release]
lto = true
