[workspace]
resolver = "2"
members = [
    "crates/github-actions-expressions",
    "crates/test-support",
    "crates/zizmor",
]

[workspace.package]
authors = ["William Woodruff <william@yossarian.net>"]
readme = "README.md"
homepage = "https://docs.zizmor.sh"
edition = "2024"
license = "MIT"

[workspace.dependencies]
anyhow = "1.0.98"
github-actions-expressions = { path = "crates/github-actions-expressions", version = "*" }
itertools = "0.14.0"
pest = "2.8.0"
pest_derive = "2.8.0"
regex = "1.11.1"

# dev-deps
assert_cmd = "2.0.17"
criterion = "0.5.1"
pretty_assertions = "1.4.1"
test-support = { path = "crates/test-support", version = "*" }


[profile.dev.package]
insta.opt-level = 3

[profile.release]
lto = true
