[package]
name = "zizmor"
description = "Static analysis for GitHub Actions"
version = "0.6.0"
edition = "2021"
repository = "https://github.com/woodruffw/zizmor"
homepage = "https://github.com/woodruffw/zizmor"
authors = ["William Woodruff <william@yossarian.net>"]
license = "MIT"
rust-version = "1.80.1"

[dependencies]
annotate-snippets = "0.11.4"
anstream = "0.6.18"
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive", "env"] }
clap-verbosity-flag = "3.0.0"
env_logger = "0.11.5"
github-actions-models = "0.9.0"
human-panic = "2.0.1"
indicatif = "0.17.9"
itertools = "0.13.0"
log = "0.4.22"
moka = { version = "0.12.8", features = ["sync"] }
owo-colors = "4.1.0"
pest = "2.7.14"
pest_derive = "2.7.14"
regex = "1.11.1"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
serde = { version = "1.0.215", features = ["derive"] }
serde-sarif = "0.6.5"
serde_json = "1.0.133"
serde_yaml = "0.9.34"
terminal-link = "0.1.0"
yamlpath = "0.12.0"

[profile.release]
lto = true

[dev-dependencies]
assert_cmd = "2.0.16"
pretty_assertions = "1.4.1"
serde_json_path = "0.7.1"
