[package]
name = "zizmor"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/woodruffw/zizmor"
homepage = "https://github.com/woodruffw/zizmor"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.16", features = ["derive", "env"] }
clap-verbosity-flag = "2.2.1"
env_logger = "0.11.5"
github-actions-models = "0.6.0"
itertools = "0.13.0"
log = "0.4.22"
regex = "1.10.6"
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
serde = { version = "1.0.208", features = ["derive"] }
serde-sarif = "0.6.5"
serde_json = "1.0.125"
serde_yaml = "0.9.34"
yamlpath = "0.4.1"
