[package]
name = "zizmor"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/woodruffw/zizmor"
homepage = "https://github.com/woodruffw/zizmor"
authors = ["William Woodruff <william@yossarian.net>"]
rust-version = "1.80.1"

[dependencies]
annotate-snippets = "0.11.4"
anstream = "0.6.15"
anyhow = "1.0.86"
clap = { version = "4.5.16", features = ["derive", "env"] }
clap-verbosity-flag = "2.2.1"
env_logger = "0.11.5"
github-actions-models = "0.7.0"
human-panic = "2.0.1"
indicatif = "0.17.8"
itertools = "0.13.0"
log = "0.4.22"
moka = { version = "0.12.8", features = ["sync"] }
owo-colors = "4.1.0"
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
serde = { version = "1.0.208", features = ["derive"] }
serde-sarif = "0.6.5"
serde_json = "1.0.125"
serde_yaml = "0.9.34"
yamlpath = "0.11.1"
