[workspace]
resolver = "2"
members = ["crates/github-actions-expressions", "crates/zizmor"]

[workspace.package]
authors = ["William Woodruff <william@yossarian.net>"]
readme = "README.md"
homepage = "https://docs.zizmor.sh"
edition = "2024"
license = "MIT"

[workspace.dependencies]
anyhow = "1.0.98"
github-actions-expressions = { path = "crates/github-actions-expressions", version = "*" }
itertools = "0.14.0"
pest = "2.8.0"
pest_derive = "2.8.0"

# dev-dep
pretty_assertions = "1.4.1"
annotate-snippets = "0.11.5"
anstream = "0.6.18"
assert_cmd = "2.0.17"
camino = "1.1.9"
clap = "4.5.38"
clap-verbosity-flag = { version = "3.0.2", default-features = false }
clap_complete = "4.5.50"
etcetera = "0.10.0"
flate2 = "1.1.1"
github-actions-models = "0.28.2"
http-cache-reqwest = "0.15.1"
human-panic = "2.0.1"
ignore = "0.4.23"
indexmap = "2.9.0"
indicatif = "0.17.11"
insta = "1.43.0"
jsonschema = "0.30.0"
line-index = "0.1.2"
owo-colors = "4.2.0"
regex = "1.11.1"
reqwest = { version = "0.12.15", default-features = false }
reqwest-middleware = "0.4.2"
serde = "1.0.219"
serde-sarif = "0.8.0"
serde_json = "1.0.140"
serde_json_path = "0.7.2"
serde_yaml = "0.9.34"
tar = "0.4.44"
terminal-link = "0.1.0"
thiserror = "2.0.12"
tokio = "1.45.0"
tracing = "0.1.41"
tracing-indicatif = "0.3.9"
tracing-subscriber = "0.3.19"
tree-sitter = "0.25.4"
tree-sitter-bash = "0.23.3"
tree-sitter-powershell = "0.25.2"
yamlpath = "0.16.0"


[profile.dev.package]
insta.opt-level = 3

[profile.release]
lto = true
