blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://discord.com/invite/PGU3zGZuGG
    about: Join our Discord server to chat with the community.
  - name: Discussions Forum
    url: https://github.com/zizmorcore/zizmor/discussions
    about: You can use our GitHub Discussions forum to ask questions and share ideas.
  - name: Security Reports
    url: https://github.com/zizmorcore/zizmor/security/advisories
    about: Please report potential security vulnerabilities here.
