name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Format
        run: cargo fmt && git diff --exit-code

      - name: Lint
        run: cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        persist-credentials: false

    - name: Test
      run: cargo test

    - name: Test snippets
      run: |
        make snippets
        git diff --exit-code
