name: zizmor binary releases for GitHub 🐙

on:
  workflow_dispatch:
  release:
    types: [published]
  pull_request:

permissions: {}

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - runner: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
          - runner: macos-latest
            target: x86_64-apple-darwin
          - runner: macos-latest
            target: aarch64-apple-darwin
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
          - runner: windows-latest
            target: i686-pc-windows-msvc

    runs-on: ${{ matrix.runner }}

    name: Release build for ${{ matrix.target }} on ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Rust toolchain and target information
        run: |
          rustup show

      - name: Install Rust target for ${{ matrix.target }}
        run: rustup target add "${TARGET}"
        env:
          TARGET: ${{ matrix.target }}

      - name: Build release
        run: cargo build --release --target "${TARGET}"
        env:
          TARGET: ${{ matrix.target }}

