name: Test SARIF Presentation

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

permissions: {}

jobs:
  test-sarif-presentation:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'test-sarif-presentation')
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2

      - name: Run zizmor
        run: |
          cargo run -- --format sarif . > results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@6bb031afdd8eb862ea3fc1848194185e076637e5 # v3.28.11
        with:
          sarif_file: results.sarif
          category: zizmor-test-sarif-presentation
