# https://github.com/woodruffw/zizmor
name: GitHub Actions Security Analysis with Zizmor

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

permissions:
  contents: read

jobs:
  zizmor:
    name: Zizmor latest via Cargo
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1
      - name: Get zizmor
        run: cargo install zizmor
      - name: Run zizmor
        run: zizmor --format sarif . > results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@0c5cd989aab6751b7c828bd77d7ae4d824554792 # v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: zizmor
